### ISSUE TITLE
SSD13006会报错，AttributeError: 'SSD1306_I2C' object has no attribute 'blit'

### ISSUE THREAD

**Issue by XueShaoy** [maysrp/micropython-bpv#1]
Traceback (most recent call last):
  File "<stdin>", line 34, in <module>
  File "bpv.py", line 21, in pbm
  File "bpv.py", line 10, in showN
AttributeError: 'SSD1306_I2C' object has no attribute 'blit'

**Comment by XueShaoy** [comment]
解决了，重新复制了您的ssd1306.py包就好了，感谢！！！
